"""Initial migration.

Revision ID: b1693115515b
Revises: 
Create Date: 2023-02-10 17:30:34.643642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1693115515b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('middlename', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('dayphone', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('mobilenumber', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('worknumber', sa.String(length=15), nullable=True))
        batch_op.drop_column('rating')
        batch_op.drop_column('title')
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('worknumber')
        batch_op.drop_column('mobilenumber')
        batch_op.drop_column('dayphone')
        batch_op.drop_column('email')
        batch_op.drop_column('lastname')
        batch_op.drop_column('middlename')
        batch_op.drop_column('firstname')

    # ### end Alembic commands ###
